services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - pokinator-network

networks:
  pokinator-network:
    name: pokinator-network
    external: true